### ISSUE TITLE
After upgrade from 2.29.1 to 2.30.0 get "Parse errors" in react-toastify: "parser.parse is not a function (undefined:undefined)  import/no-deprecated"

### ISSUE THREAD

**Issue by corneliusroemer** [import-js/eslint-plugin-import#3058]
When upgrading eslint-plugin-import from 2.29.1 to 2.30.0 I suddenly get an error for react-toastify.esm.mjs:

```
Error:   3:32  error  Parse errors in imported module 'react-toastify': parser.parse is not a function (undefined:undefined)  import/no-deprecated
```

is this intended?

```
Error while parsing /codebuild/output/src262100263/src/actions-runner/_work/loculus/loculus/website/node_modules/react-toastify/dist/react-toastify.esm.mjs
Line 4, column 0: Unknown token at 15458, expected: "}", actual: ""
`parseForESLint` from parser `/codebuild/output/src262[10](https://github.com/loculus-project/loculus/actions/runs/10779022293/job/29891619759?pr=2732#step:6:11)0263/src/actions-runner/_work/loculus/loculus/website/node_modules/astro-eslint-parser/lib/index.js` is invalid and will just be ignored

/codebuild/output/src262100263/src/actions-runner/_work/loculus/loculus/website/src/layouts/BaseLayout.astro
Error:   3:32  error  Parse errors in imported module 'react-toastify': parser.parse is not a function (undefined:undefined)  import/no-deprecated
```
see https://github.com/loculus-project/loculus/actions/runs/10779022293/job/29891619759?pr=2732#step:6:10

I don't know enough about react-toastify and eslint-plugin-import and JS/TS in general to know where the error lies.

Discovered in this dependabot PR: https://github.com/loculus-project/loculus/pull/2732

See issue in react-toastify: https://github.com/fkhadra/react-toastify/issues/1154

**Comment by ljharb** [comment]
As you can see here: https://github.com/loculus-project/loculus/actions/runs/10779022293/job/29891619759?pr=2732#step:6:12 the problem is with `astro-eslint-parser`.

**Comment by corneliusroemer** [comment]
Thanks! Strangely I can't reproduce actually after a fresh checkout and `npm ci`.

**Comment by corneliusroemer** [comment]
Wait, I _can_ reproduce it again. The eslint cache might have thrown me.

The error _does_ get triggered by the upgrade to 2.30.0. It might well be that the astro-eslint-parser contributes but some code change in `eslint-plug-import` makes it happen only now.

**Comment by ljharb** [comment]
and you're sure it's not from updating `@typescript-eslint/parser`? (the astro parser wraps that)

**Comment by corneliusroemer** [comment]
Yep, that one's still bumped here and it doesn't error (in that place): https://github.com/loculus-project/loculus/actions/runs/10781731886/job/29900275170?pr=2739

**Comment by ljharb** [comment]
Does it happen with v2.29.1 of the import plugin and v2.10.0 of eslint-module-utils?

**Comment by corneliusroemer** [comment]
Nope, doesn't happen in that case, that diff doesn't trigger it either:

<img width="1416" alt="image" src="https://github.com/user-attachments/assets/263bb7f4-ffad-442e-8415-ff000c811393">

**Comment by ljharb** [comment]
What version did you have previously? 1079e70f is the only change in v2.10.0 that's not in v2.9.0, and that doesn't seem like it could be relevant. 806e3c2c was added in v2.9.0, but that only added `.mjs` and `.cjs` as valid default extensions.

**Comment by corneliusroemer** [comment]
2.8.1, see screenshot above

**Comment by ljharb** [comment]
ah, thanks :-) could you try v2.8.2 and v2.9.0, just to be sure?

**Comment by corneliusroemer** [comment]
Indeed it is the upgrade from 2.8.2 -> 2.9.0

<details>

```
❯ npm ci
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

added 1180 packages, and audited 1181 packages in 28s

390 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

loculus/website on  dependabot/npm_and_yarn/website/minorandpatch-b0e14b6152 [$?] is 📦 v0.0.1 via  v22.8.0 in ☸ aws (default) on ☁️  (us-east-1) took 28s
❯ npm exec eslint /Users/corneliusromer/code/loculus/website/src/layouts/BaseLayout.astro
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.2

Please only submit bug reports when using the officially supported version.

=============

loculus/website on  dependabot/npm_and_yarn/website/minorandpatch-b0e14b6152 [$?] is 📦 v0.0.1 via  v22.8.0 in ☸ aws (default) on ☁️  (us-east-1) took 6s
❯ npm i eslint-module-utils@2.10.0

changed 1 package, and audited 1181 packages in 1s

390 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

loculus/website on  dependabot/npm_and_yarn/website/minorandpatch-b0e14b6152 [$!?] is 📦 v0.0.1 via  v22.8.0 in ☸ aws (default) on ☁️  (us-east-1)
❯ npm exec eslint /Users/corneliusromer/code/loculus/website/src/layouts/BaseLayout.astro
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.2

Please only submit bug reports when using the officially supported version.

=============

Error while parsing /Users/corneliusromer/code/loculus/website/node_modules/react-toastify/dist/react-toastify.esm.mjs
Line 4, column 0: Unknown token at 15458, expected: "}", actual: ""
`parseForESLint` from parser `/Users/corneliusromer/code/loculus/website/node_modules/astro-eslint-parser/lib/index.js` is invalid and will just be ignored

/Users/corneliusromer/code/loculus/website/src/layouts/BaseLayout.astro
  3:32  error  Parse errors in imported module 'react-toastify': parser.parse is not a function (undefined:undefined)  import/no-deprecated

✖ 1 problem (1 error, 0 warnings)


```

</details>

**Comment by ljharb** [comment]
cc @michaelfaith it'd be great to get a fix for this in its own PR/commit (i think you may already be looking at it for #2996)

**Comment by michaelfaith** [comment]
Do you have a repo that'd can easily reproduce this, or steps to reproduce it in this repo's examples?  That'll help with testing and validation.
Also maybe it is the `mjs` / `cjs` addition after all?  I wouldn't have thought that'd have causes such a thing, but I notice the path in the parsing error has an `mjs` extension.  Is the `astrolint-eslint-parser` able to parse esm files?
Either way, if I can reliably reproduce it, I'll work on putting a fix up.

**Comment by michaelfaith** [comment]
@corneliusroemer just checking in, did you still want me to take a look at this?  If so, any repro steps or a minimum reproduction repo demonstrating the issue would be super helpful.

**Comment by ljharb** [comment]
Glad to hear it.

**Comment by acelaya** [comment]
I see this was closed as completed, stating v2.31 fixed it, but I can still reproduce it with that version and `eslint-plugin-astro` v1.3.1 (the latest at the moment).

**Comment by ljharb** [comment]
@acelaya can you provide a repro repo?

**Comment by acelaya** [comment]
Yep, this one https://github.com/shlinkio/shlink.io

All `import` rules are disabled in `eslint.config.js` for `.astro` files: https://github.com/shlinkio/shlink.io/blob/main/eslint.config.js#L16-L25

If you comment out those and run `npm run lint`, you should be able to reproduce it, and get an output like this:

<details>

```
Error while parsing /shlink-website/node_modules/@docsearch/react/dist/esm/index.js
Line 1, column 222: Unknown token at 222, expected: "{", actual: "a(e,t,r,n,"
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@docsearch/react/dist/esm/index.js
Line 1, column 222: Unknown token at 222, expected: "{", actual: "a(e,t,r,n,"
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-solid-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/react-fontawesome/index.es.js
Line 19, column 21: Unable to assign attributes when using <> Fragment shorthand syntax! [1002]
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-solid-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/react-fontawesome/index.es.js
Line 19, column 21: Unable to assign attributes when using <> Fragment shorthand syntax! [1002]
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/react-external-link/dist/index.js
Line 2, column 17: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/react-external-link/dist/index.js
Line 2, column 17: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-brands-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-regular-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-solid-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/react-external-link/dist/index.js
Line 2, column 17: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-brands-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-regular-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-solid-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/react-external-link/dist/index.js
Line 2, column 17: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-regular-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-solid-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/react-fontawesome/index.es.js
Line 19, column 21: Unable to assign attributes when using <> Fragment shorthand syntax! [1002]
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/react-external-link/dist/index.js
Line 2, column 17: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-regular-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/free-solid-svg-icons/index.mjs
Line 8, column 8: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/@fortawesome/react-fontawesome/index.es.js
Line 19, column 21: Unable to assign attributes when using <> Fragment shorthand syntax! [1002]
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

Error while parsing /shlink-website/node_modules/react-external-link/dist/index.js
Line 2, column 17: '}' expected.
`parseForESLint` from parser `context.languageOptions.parser` is invalid and will just be ignored

/shlink-website/src/layouts/DocsLayout.astro
  2:27  error  Parse errors in imported module '@docsearch/react': parser.parse is not a function (undefined:undefined)  import/namespace

/shlink-website/src/pages/404.astro
  2:35  error  Parse errors in imported module '@fortawesome/free-solid-svg-icons': parser.parse is not a function (undefined:undefined)  import/namespace
  3:33  error  Parse errors in imported module '@fortawesome/react-fontawesome': parser.parse is not a function (undefined:undefined)     import/namespace

/shlink-website/src/pages/apps.astro
  2:30  error  Parse errors in imported module 'react-external-link': parser.parse is not a function (undefined:undefined)  import/namespace

/shlink-website/src/pages/features.astro
   2:26  error  Parse errors in imported module '@fortawesome/free-brands-svg-icons': parser.parse is not a function (undefined:undefined)   import/namespace
   3:40  error  Parse errors in imported module '@fortawesome/free-regular-svg-icons': parser.parse is not a function (undefined:undefined)  import/namespace
  20:8   error  Parse errors in imported module '@fortawesome/free-solid-svg-icons': parser.parse is not a function (undefined:undefined)    import/namespace
  21:30  error  Parse errors in imported module 'react-external-link': parser.parse is not a function (undefined:undefined)                  import/namespace

/shlink-website/src/pages/index.astro
  2:28  error  Parse errors in imported module '@fortawesome/free-regular-svg-icons': parser.parse is not a function (undefined:undefined)  import/namespace
  3:95  error  Parse errors in imported module '@fortawesome/free-solid-svg-icons': parser.parse is not a function (undefined:undefined)    import/namespace
  4:33  error  Parse errors in imported module '@fortawesome/react-fontawesome': parser.parse is not a function (undefined:undefined)       import/namespace
  5:30  error  Parse errors in imported module 'react-external-link': parser.parse is not a function (undefined:undefined)                  import/namespace

✖ 12 problems (12 errors, 0 warnings)
```

</details>

**Comment by JounQin** [comment]
@acelaya You need to config a correct ESLint parser for `.astro` as https://github.com/import-js/eslint-plugin-import#importparsers

**Comment by acelaya** [comment]
> [@acelaya](https://github.com/acelaya) You need to config a correct ESLint parser for `.astro` as https://github.com/import-js/eslint-plugin-import#importparsers

Hmm, yeah, that seems like it should fix it. I also see some threads in eslint-plugin-astro repository recommending the same, but all of them (including the one you linked) seem to still use the legacy eslint config format.

Using the supposedly equivalent in flat config, doesn't seem to help, or I'm not doing it properly. The general documentation around flat config migration is a bit spread in a number of places, so it could be my fault.

I applied this diff, and yet it keeps throwing the same errors:

<details>

```diff
diff --git a/eslint.config.js b/eslint.config.js
index 2f50260..8c0df1f 100644
--- a/eslint.config.js
+++ b/eslint.config.js
@@ -1,28 +1,23 @@
 import shlink from '@shlinkio/eslint-config-js-coding-standard';
+import { defineConfig } from 'eslint/config';
 import eslintPluginAstro from 'eslint-plugin-astro';
 
 /* eslint-disable-next-line no-restricted-exports */
-export default [
-  ...shlink,
-  ...eslintPluginAstro.configs.recommended,
+export default defineConfig(
+  shlink,
 
   {
     files: ['**/*.astro'],
+    extends: eslintPluginAstro.configs.recommended,
+    settings: {
+      'import/parsers': {
+        'astro-eslint-parser': ['.astro'],
+      },
+    },
     rules: {
       // Linter is throwing a false positive on the usage of `class` property when it should be className, but in astro
       // files, `class` is correct
       'react/no-unknown-property': ['error', { ignore: ['class'] }],
-
-      // Disable eslint-plugin-import rules in astro files, as they throw an error
-      // See https://github.com/import-js/eslint-plugin-import/issues/3058
-      'import/no-unresolved': 'off',
-      'import/named': 'off',
-      'import/namespace': 'off',
-      'import/default': 'off',
-      'import/export': 'off',
-      'import/no-named-as-default': 'off',
-      'import/no-named-as-default-member': 'off',
-      'import/no-duplicates': 'off',
     },
   },
-];
+);
```

</details>

**Comment by JounQin** [comment]
```diff
diff --git a/eslint.config.js b/eslint.config.js
index 2f50260..c953045 100644
--- a/eslint.config.js
+++ b/eslint.config.js
@@ -1,28 +1,29 @@
 import shlink from '@shlinkio/eslint-config-js-coding-standard';
+import { defineConfig } from 'eslint/config';
 import eslintPluginAstro from 'eslint-plugin-astro';
 
 /* eslint-disable-next-line no-restricted-exports */
-export default [
+export default defineConfig(
   ...shlink,
-  ...eslintPluginAstro.configs.recommended,
-
+  {
+    languageOptions: {
+      sourceType: 'module',
+      ecmaVersion: 'latest',
+    },
+  },
   {
     files: ['**/*.astro'],
+    extends: eslintPluginAstro.configs['flat/recommended'],
+    settings: {
+      'import/parsers': {
+        'astro-eslint-parser': ['.astro'],
+        espree: ['.js', '.mjs'],
+      },
+    },
     rules: {
       // Linter is throwing a false positive on the usage of `class` property when it should be className, but in astro
       // files, `class` is correct
       'react/no-unknown-property': ['error', { ignore: ['class'] }],
-
-      // Disable eslint-plugin-import rules in astro files, as they throw an error
-      // See https://github.com/import-js/eslint-plugin-import/issues/3058
-      'import/no-unresolved': 'off',
-      'import/named': 'off',
-      'import/namespace': 'off',
-      'import/default': 'off',
-      'import/export': 'off',
-      'import/no-named-as-default': 'off',
-      'import/no-named-as-default-member': 'off',
-      'import/no-duplicates': 'off',
     },
   },
-];
+);
```

**Comment by acelaya** [comment]
Oh thanks! That worked indeed.

I think the language options should not be needed if the `react-external-link` library was not stating its an ESM but exposing a CommonJS module. I maintain that library, so I should be able to fix that.

Really appreciate your time, specially considering I did not get to provide a proper minimal reproduction 🙂

**Comment by JounQin** [comment]
@acelaya It's not `react-external-link`'s fault, it has correct `module`/`exports` entries. So, `.js` should be treated as `module`.

Additionally, `eslint-plugin-import` doesn't recognize `exports` currently, you can try https://github.com/import-js/eslint-import-resolver-typescript.
