### ISSUE TITLE
Error: Failed to load plugin 'import' declared in '.eslintrc': Cannot find module 'typescript/package.json' 2.27.0

### ISSUE THREAD

**Issue by DerekWW** [import-js/eslint-plugin-import#2665]
Lint jobs suddenly started failing with the following:
```
Error: Failed to load plugin 'import' declared in '.eslintrc': Cannot find module 'typescript/package.json'
```
After some digging it appears that 2.27.0  of eslint-plugin-import is breaking my pipeline. I have pinned to 2.26.0 and that has solved my issue. I have not investigated what the root cause may have been.

Node: 14.15.4
ESlint: 7.32.0

**Comment by davidrunger** [comment]
This is a dupe of this issue: https://github.com/import-js/eslint-plugin-import/issues/2663.

**Comment by ljharb** [comment]
I'm not sure why `typescript/package.json` wouldn't be findable.

**Comment by ljharb** [comment]
v2.27.1 is released, but I'm not sure if that fixes this problem or not.

**Comment by ljharb** [comment]
ah, found it - this was caused by #2475. I'll have a fix ready and released shortly.

**Comment by ljharb** [comment]
v2.27.2 is released.

**Comment by DerekWW** [comment]
Thanks so much!

**Comment by matthew-charles-chan** [comment]
Thank you for the quick fix and release!

**Comment by norayr93** [comment]
It's still broken in 2.29.x version

**Comment by ljharb** [comment]
@norayr93 please file a new issue, then
